import axios from 'axios'
import store from '../store'
import { apiUrl } from '../config'

const http = axios.create({
  baseURL: apiUrl,
})

http.interceptors.response.use(
  response => response,
  /**
  * This is a central point to handle all
  * error messages generated by HTTP
  * requests
  */
  (error) => {
    store.dispatch('setMessage', { type: 'error', message: error.response.data.messages })
  }
)

export default function install(Vue) {
  Object.defineProperties(Vue.prototype, {
    $http: {
      get() {
        return http
      },
    },
  })
}
