
export const MAIN_SET_TOKEN = 'MAIN_SET_TOKEN'
export const MAIN_SET_USER = 'MAIN_SET_USER'
export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'

export const CATEGORIES_SET_LIST = 'CATEGORIES_SET_LIST'
